name: Deploy to surge

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: yarn
      - name: Build project
        run: yarn build
      - name: Deploy to surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'mvst-base-design-system.surge.sh'
          project: './dist'
          login: ${{ secrets.SURGE_USER }}
          token: ${{ secrets.SURGE_TOKEN }}
